name: speakAny
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  hexcolor: ^1.0.2
  outline_material_icons: ^0.1.1
  flutter_icons: ^1.1.0
  firebase_auth: ^0.16.1
  firebase_storage:
  image_picker: 
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  shared_preferences: ^0.5.7+3
  country_list_pick: ^1.0.0+4
  language_pickers: ^0.2.0+1
  flutter_country_picker: ^0.1.6
  permission_handler: ^5.0.1+1
  youtube_player_flutter: ^6.1.0+7
  get: ^3.2.2
  cached_network_image: ^2.2.0+1
  audioplayer:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/ic_imslogo.png
    - assets/images/googlelogo.png
    - assets/images/fblogo.jpg
    - assets/images/twitterlogo.jpg
    - assets/images/ulogo.png
    - assets/images/ulogo.jpg
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/splash.jpeg
    - assets/images/logo.jpeg
    - assets/images/siginlogo.png

    - assets/images/t1.jpeg
    - assets/images/t2.jpeg
    - assets/images/t3.jpeg
    - assets/images/t4.jpeg
    - assets/images/t5.jpeg
    - assets/images/t6.jpeg
    - assets/images/t7.jpeg
    - assets/images/US.png
    - assets/images/pak.png
    - assets/images/ind.png
    - assets/images/canada.png
    - assets/images/china.png
    - assets/images/iran.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
